### ISSUE TITLE
Bevy docs don't show code behind not active flags

### ISSUE THREAD

**Issue by ameknite** [bevyengine/bevy#10498]
## Bevy version

0.12

## What you did

While reading the Bevy 0.12 news on the website, I encountered a link to the documentation that doesn't work

https://docs.rs/bevy/0.12.0/bevy/render/texture/struct.CompressedImageSaver.html

The link is correct, but it doesn't work because the struct is behind a feature flag that is not active by default:

```
#[cfg(feature = "basis-universal")]
pub use compressed_image_saver::*;
```

When I run `cargo doc --features basis-universal`, the struct appears in the local docs.

## What went wrong

It looks like you need to enable the flags for the code to appear in the docs

I'm unsure if there is a way to upload the documentation with `cargo doc --all-features` to docs.rs.

**Comment by mockersf** [comment]
It's possible, see https://docs.rs/about/metadata
But you hit the opposite issue with people finding something in doc they won't in their IDE. I think there's is work on rustic to be able to automatically mark functions behind a feature with that feature

**Comment by hoijui** [comment]
I hit this same issue looking at <https://docs.rs/bevy_ui/latest/bevy_ui/>, where it links to `TextBundle` which is behind the `bevy_text` feature.

In my eyes, it would be much better for people to see doc in the browser that they do not see in their IDE, then not seeing it anywhere. Imagine someone needs the functionality that `TextBundle` offers. they do not find it neither in the IDE nor in the browser, so they start searching all the web, or worse, even try to put something together by themself.
If they have it in the browser but not the IDE, they will at least look in the right places, maybe ask in a chat or an issue, and eventually they get to the flag and may even create a PR to manually document that the flag is required.
I agree.. it is not the best argument, but .. I see a slight benefit of this way over the current one.

**Comment by bugsweeper** [comment]
It had been fixed in #12366 and code allready appeared in [dev-docs](https://dev-docs.bevyengine.org/bevy/render/texture/struct.CompressedImageSaver.html)

**Comment by ameknite** [comment]
Fixed in https://github.com/bevyengine/bevy/pull/12366

**Comment by GitGhillie** [comment]
I still cannot find CompressedImageSaver in the docs: https://docs.rs/bevy/latest/bevy/index.html?search=CompressedImageSaver
Or should I be pointing users to the dev-docs?

**Comment by bugsweeper** [comment]
You will be able to find after 0.14 release, dev-docs is a preview of future version. If some fix is made after release, it will appear in the next release. 0.14 should be ready in a few weeks

**Comment by ameknite** [comment]
No many people knows about it. You could also use: https://dev-docs.bevyengine.org/bevy/ , but I don't know if it sync correctly with docs.rs

Here is the link:
https://dev-docs.bevyengine.org/bevy/render/texture/struct.CompressedImageSaver.html

**Comment by bugsweeper** [comment]
> No many people knows about it.

This information described in CONTRIBUTING.md page at `Writing docs` section
