### ISSUE TITLE
Build errors with webgpu

### ISSUE THREAD

**Issue by smessmer** [bevyengine/bevy#10583]
## Bevy version

0.12

## Relevant system information

Ubuntu 22.04.3
cargo 1.76.0-nightly (6790a5127 2023-11-10)
Bevy features:
```
[
  "animation",
  "bevy_asset",
  "bevy_gilrs",
  "bevy_scene",
  "bevy_winit",
  "bevy_core_pipeline",
  "bevy_pbr",
  "bevy_gltf",
  "bevy_render",
  "bevy_sprite",
  "bevy_text",
  "bevy_ui",
  "multi-threaded",
  "png",
  "hdr",
  "x11",
  "bevy_gizmos",
  "android_shared_stdcxx",
  "tonemapping_luts",
  "default_font",
]
```

## What you did

Build or serve the game using trunk. I remember that a while ago, this correctly worked but at some point it must have stopped working because I'm now seeing compiler errors. Possibly due to an upgrade of the rust compiler to a newer nightly version. It previously built correctly both with and without the `webgl/webgl2` feature flag. Now, however, it only builds if I specify the `webgl/webgl2` feature flag. Without the feature flag, I run into the issue below.

I first noticed this after upgrading from bevy 0.11 to bevy 0.12, but I can now also reproduce it with bevy 0.11 so doesn't seem related to the bevy version upgrade.

## What went wrong

```
$ trunk build
[...]
error[E0061]: this function takes 3 arguments but 1 argument was supplied
   --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.17.1/src/backend/web.rs:386:22
    |
386 |     let mut mapped = web_sys::GpuDepthStencilState::new(map_texture_format(desc.format));
    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^--------------------------------- two arguments of type `GpuCompareFunction` and `bool` are missing
    |
note: associated function defined here
   --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/web-sys-0.3.65/src/features/gen_GpuDepthStencilState.rs:27:12
    |
27  |     pub fn new(
    |            ^^^
help: provide the arguments
    |
386 |     let mut mapped = web_sys::GpuDepthStencilState::new(/* GpuCompareFunction */, /* bool */, map_texture_format(desc.format));
    |                                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

error[E0308]: mismatched types
    --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.17.1/src/backend/web.rs:2610:17
     |
2608 |             .set_bind_group_with_u32_array_and_f64_and_dynamic_offsets_data_length(
     |              --------------------------------------------------------------------- arguments to this method are incorrect
2609 |                 index,
2610 |                 &bind_group_data.0,
     |                 ^^^^^^^^^^^^^^^^^^ expected `Option<&GpuBindGroup>`, found `&GpuBindGroup`
     |
     = note:   expected enum `Option<&GpuBindGroup>`
             found reference `&GpuBindGroup`
note: method defined here
    --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/web-sys-0.3.65/src/features/gen_GpuComputePassEncoder.rs:201:12
     |
201  |     pub fn set_bind_group_with_u32_array_and_f64_and_dynamic_offsets_data_length(
     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
help: try wrapping the expression in `Some`
     |
2610 |                 Some(&bind_group_data.0),
     |                 +++++                  +

error[E0308]: mismatched types
    --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.17.1/src/backend/web.rs:2735:17
     |
2733 |             .set_bind_group_with_u32_array_and_f64_and_dynamic_offsets_data_length(
     |              --------------------------------------------------------------------- arguments to this method are incorrect
2734 |                 index,
2735 |                 &bind_group_data.0,
     |                 ^^^^^^^^^^^^^^^^^^ expected `Option<&GpuBindGroup>`, found `&GpuBindGroup`
     |
     = note:   expected enum `Option<&GpuBindGroup>`
             found reference `&GpuBindGroup`
note: method defined here
    --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/web-sys-0.3.65/src/features/gen_GpuRenderBundleEncoder.rs:131:12
     |
131  |     pub fn set_bind_group_with_u32_array_and_f64_and_dynamic_offsets_data_length(
     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
help: try wrapping the expression in `Some`
     |
2735 |                 Some(&bind_group_data.0),
     |                 +++++                  +

error[E0308]: mismatched types
    --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.17.1/src/backend/web.rs:2785:21
     |
2783 |                 encoder_data.0.set_vertex_buffer_with_f64_and_f64(
     |                                ---------------------------------- arguments to this method are incorrect
2784 |                     slot,
2785 |                     &buffer_data.0,
     |                     ^^^^^^^^^^^^^^ expected `Option<&GpuBuffer>`, found `&GpuBuffer`
     |
     = note:   expected enum `Option<&GpuBuffer>`
             found reference `&GpuBuffer`
note: method defined here
    --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/web-sys-0.3.65/src/features/gen_GpuRenderBundleEncoder.rs:617:12
     |
617  |     pub fn set_vertex_buffer_with_f64_and_f64(
     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
help: try wrapping the expression in `Some`
     |
2785 |                     Some(&buffer_data.0),
     |                     +++++              +

error[E0308]: mismatched types
    --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.17.1/src/backend/web.rs:2793:55
     |
2793 |                     .set_vertex_buffer_with_f64(slot, &buffer_data.0, offset as f64);
     |                      --------------------------       ^^^^^^^^^^^^^^ expected `Option<&GpuBuffer>`, found `&GpuBuffer`
     |                      |
     |                      arguments to this method are incorrect
     |
     = note:   expected enum `Option<&GpuBuffer>`
             found reference `&GpuBuffer`
note: method defined here
    --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/web-sys-0.3.65/src/features/gen_GpuRenderBundleEncoder.rs:546:12
     |
546  |     pub fn set_vertex_buffer_with_f64(
     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
help: try wrapping the expression in `Some`
     |
2793 |                     .set_vertex_buffer_with_f64(slot, Some(&buffer_data.0), offset as f64);
     |                                                       +++++              +

error[E0308]: mismatched types
    --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.17.1/src/backend/web.rs:2950:17
     |
2948 |             .set_bind_group_with_u32_array_and_f64_and_dynamic_offsets_data_length(
     |              --------------------------------------------------------------------- arguments to this method are incorrect
2949 |                 index,
2950 |                 &bind_group_data.0,
     |                 ^^^^^^^^^^^^^^^^^^ expected `Option<&GpuBindGroup>`, found `&GpuBindGroup`
     |
     = note:   expected enum `Option<&GpuBindGroup>`
             found reference `&GpuBindGroup`
note: method defined here
    --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/web-sys-0.3.65/src/features/gen_GpuRenderPassEncoder.rs:218:12
     |
218  |     pub fn set_bind_group_with_u32_array_and_f64_and_dynamic_offsets_data_length(
     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
help: try wrapping the expression in `Some`
     |
2950 |                 Some(&bind_group_data.0),
     |                 +++++                  +

error[E0308]: mismatched types
    --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.17.1/src/backend/web.rs:3000:21
     |
2998 |                 pass_data.0.set_vertex_buffer_with_f64_and_f64(
     |                             ---------------------------------- arguments to this method are incorrect
2999 |                     slot,
3000 |                     &buffer_data.0,
     |                     ^^^^^^^^^^^^^^ expected `Option<&GpuBuffer>`, found `&GpuBuffer`
     |
     = note:   expected enum `Option<&GpuBuffer>`
             found reference `&GpuBuffer`
note: method defined here
    --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/web-sys-0.3.65/src/features/gen_GpuRenderPassEncoder.rs:704:12
     |
704  |     pub fn set_vertex_buffer_with_f64_and_f64(
     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
help: try wrapping the expression in `Some`
     |
3000 |                     Some(&buffer_data.0),
     |                     +++++              +

error[E0308]: mismatched types
    --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.17.1/src/backend/web.rs:3008:55
     |
3008 |                     .set_vertex_buffer_with_f64(slot, &buffer_data.0, offset as f64);
     |                      --------------------------       ^^^^^^^^^^^^^^ expected `Option<&GpuBuffer>`, found `&GpuBuffer`
     |                      |
     |                      arguments to this method are incorrect
     |
     = note:   expected enum `Option<&GpuBuffer>`
             found reference `&GpuBuffer`
note: method defined here
    --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/web-sys-0.3.65/src/features/gen_GpuRenderPassEncoder.rs:633:12
     |
633  |     pub fn set_vertex_buffer_with_f64(
     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
help: try wrapping the expression in `Some`
     |
3008 |                     .set_vertex_buffer_with_f64(slot, Some(&buffer_data.0), offset as f64);
     |                                                       +++++              +

Some errors have detailed explanations: E0061, E0308.
For more information about an error, try `rustc --explain E0061`.
error: could not compile `wgpu` (lib) due to 8 previous errors
warning: build failed, waiting for other jobs to finish...
2023-11-16T05:24:22.546636Z ERROR ❌ error
error from HTML pipeline

Caused by:
    0: error from asset pipeline
    1: error during cargo build execution
    2: cargo call returned a bad status
Error: error from HTML pipeline

Caused by:
    0: error from asset pipeline
    1: error during cargo build execution
    2: cargo call returned a bad status
```

**Comment by mockersf** [comment]
It should be fixed for Bevy 0.12 if you run cargo update. A patch for wgpu (0.17.2) w s published yesterday

**Comment by smessmer** [comment]
Thanks. This fixed it for bevy 0.12 but I'm still seeing the issue in bevy 0.11 where `bevy_render v0.11.3` locks `wgpu` to `v0.16.3`.

**Comment by james7132** [comment]
Unless we go back an publish 0.11 crates again, I don't think this is issue is actionable other than avoiding point version locking in the future.

**Comment by smessmer** [comment]
I'm now getting the same issue in bevy 0.12.1 with wgpu 0.17.2:

```
error[E0061]: this function takes 1 argument but 3 arguments were supplied
   --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.17.2/src/backend/web.rs:386:22
    |
386 |     let mut mapped = web_sys::GpuDepthStencilState::new(
    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
387 |         map_compare_function(desc.depth_compare),
    |         ---------------------------------------- unexpected argument of type `GpuCompareFunction`
388 |         desc.depth_write_enabled,
    |         ------------------------ unexpected argument of type `bool`
    |
note: associated function defined here
   --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/web-sys-0.3.69/src/features/gen_GpuDepthStencilState.rs:27:12
    |
27  |     pub fn new(format: GpuTextureFormat) -> Self {
    |            ^^^
help: remove the extra arguments
    |
387 -         map_compare_function(desc.depth_compare),
387 +         map_texture_format(desc.format),
    |

error[E0061]: this function takes 1 argument but 2 arguments were supplied
    --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.17.2/src/backend/web.rs:1569:13
     |
1569 |             web_sys::GpuVertexState::new(desc.vertex.entry_point, &module.0);
     |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ -------------------------
     |                                          |
     |                                          unexpected argument of type `&str`
     |                                          help: remove the extra argument
     |
note: associated function defined here
    --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/web-sys-0.3.69/src/features/gen_GpuVertexState.rs:27:12
     |
27   |     pub fn new(module: &GpuShaderModule) -> Self {
     |            ^^^

error[E0061]: this function takes 2 arguments but 3 arguments were supplied
    --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.17.2/src/backend/web.rs:1644:17
     |
1644 |                 web_sys::GpuFragmentState::new(frag.entry_point, &module.0, &targets);
     |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ----------------             -------- unexpected argument of type `&js_sys::Array`
     |                                                |
     |                                                expected `&GpuShaderModule`, found `&str`
     |
     = note: expected reference `&GpuShaderModule`
                found reference `&str`
note: associated function defined here
    --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/web-sys-0.3.69/src/features/gen_GpuFragmentState.rs:27:12
     |
27   |     pub fn new(module: &GpuShaderModule, targets: &::wasm_bindgen::JsValue) -> Self {
     |            ^^^
help: remove the extra argument
     |
1644 -                 web_sys::GpuFragmentState::new(frag.entry_point, &module.0, &targets);
1644 +                 web_sys::GpuFragmentState::new(/* &GpuShaderModule */, &module.0);
     |

error[E0061]: this function takes 1 argument but 2 arguments were supplied
    --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.17.2/src/backend/web.rs:1669:13
     |
1669 |             web_sys::GpuProgrammableStage::new(desc.entry_point, &shader_module.0);
     |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ------------------
     |                                                |
     |                                                unexpected argument of type `&str`
     |                                                help: remove the extra argument
     |
note: associated function defined here
    --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/web-sys-0.3.69/src/features/gen_GpuProgrammableStage.rs:27:12
     |
27   |     pub fn new(module: &GpuShaderModule) -> Self {
     |            ^^^

error[E0599]: no method named `write_timestamp` found for struct `GpuCommandEncoder` in the current scope
    --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.17.2/src/backend/web.rs:2360:14
     |
2358 | /         encoder_data
2359 | |             .0
2360 | |             .write_timestamp(&query_set_data.0, query_index);
     | |             -^^^^^^^^^^^^^^^ method not found in `GpuCommandEncoder`
     | |_____________|
     | 

Some errors have detailed explanations: E0061, E0599.
For more information about an error, try `rustc --explain E0061`.
error: could not compile `wgpu` (lib) due to 5 previous errors
warning: build failed, waiting for other jobs to finish...
2024-03-16T21:46:44.817552Z ERROR ❌ error
error from HTML pipeline

Caused by:
    0: error from asset pipeline
    1: error during cargo build execution
    2: cargo call returned a bad status                                                            
```

**Comment by mockersf** [comment]
This is because `web-sys` publish new versions with breaking changes, as the webgpu apis are unstable. This should not be a problem anymore as `wgpu` now doesn't depend on `web-sys` for those anymore, but it still did in Bevy 0.12. You should use a pinned [version of `web-sys` from around that time](https://crates.io/crates/web-sys/versions), so maybe the 0.3.66?
