### ISSUE TITLE
`DenseAssetStorage<bevy_gltf::Gltf>::insert`: 'internal error: entered unreachable code: entries should always be valid after a flush'.

### ISSUE THREAD

**Issue by marcelchampagne** [bevyengine/bevy#10820]
## Bevy version
`0.12.1`

## Relevant system information
```
2023-11-30T22:47:50.264801Z  INFO bevy_render::renderer: AdapterInfo { name: "AMD Radeon RX 5700 XT", vendor: 4098, device: 29471, device_type: DiscreteGpu, driver: "AMD proprietary driver", driver_info: "23.9.2 (AMD proprietary shader compiler)", backend: Vulkan }
2023-11-30T22:47:50.510744Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "Windows 10 Home", kernel: "19045", cpu: "AMD Ryzen 7 3700X 8-Core Processor", core_count: "8", memory: "15.9 GiB" }
```

## What you did
I have a simple asset plugin that loads GLB files and inserts the handles for the scenes and meshes into a resource. In my full application, which loads approximately 200 assets, I encounter a panic immediately after running cargo run after upgrading to Bevy 0.12.1 from 0.11.3.

I've provided an MRE below. Unfortunately, with the below example, the panic only occurs, roughly, 1 out of every 50 times. In my full application, it seems to happen much more frequently, perhaps 1 out of every 10 runs.

```
use bevy::{prelude::*, utils::HashMap};

#[derive(Debug, Clone, Copy, Default, Eq, PartialEq, Hash, States)]
pub enum GameState {
    #[default]
    LoadingAssets,
}

#[derive(Default, Debug, Clone, Copy, PartialEq, Eq, Hash, Component)]
pub enum Model {
    #[default]
    AlpacaBaby,
    AlpacaAdolescent,
    AlpacaMature,
    CowBaby,
    CowAdolescent,
    CowMature,
    Alligasaur,
    Deer,
    Fox,
    Wolf,
    Player,
    Man,
    Woman,
}

#[derive(Resource, Default)]
pub struct Scenes {
    pub scene_registry: HashMap<Model, Handle<Scene>>,
}

#[derive(Resource, Default)]
pub struct Meshes {
    pub mesh_registry: HashMap<Model, Handle<Mesh>>,
}

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_plugins(AssetPlugin)
        .run();
}

struct AssetPlugin;

impl Plugin for AssetPlugin {
    fn build(&self, app: &mut App) {
        app.add_state::<GameState>()
            .init_resource::<Scenes>()
            .init_resource::<Meshes>()
            .add_systems(OnEnter(GameState::LoadingAssets), setup_models_system);
    }
}

pub fn setup_models_system(
    mut scenes: ResMut<Scenes>,
    mut meshes: ResMut<Meshes>,
    asset_server: Res<AssetServer>,
) {
    let entries = [
        (Model::AlpacaBaby, "alpaca_baby.glb"),
        (Model::AlpacaAdolescent, "alpaca_adolescent.glb"),
        (Model::AlpacaMature, "alpaca_mature.glb"),
        (Model::CowBaby, "cow_baby.glb"),
        (Model::CowAdolescent, "cow_adolescent.glb"),
        (Model::CowMature, "cow_mature.glb"),
        (Model::Alligasaur, "alligasaur.glb"),
        (Model::Deer, "deer.glb"),
        (Model::Player, "player.glb"),
        (Model::Man, "man.glb"),
        (Model::Woman, "woman.glb"),
    ];

    let mut scene_registry: HashMap<Model, Handle<Scene>> = HashMap::new();
    let mut mesh_registry: HashMap<Model, Handle<Mesh>> = HashMap::new();
    for (model, path) in entries.iter() {
        scene_registry.insert(*model, asset_server.load(format!("{}#Scene0", path)));
        mesh_registry.insert(
            *model,
            asset_server.load(format!("{}#Mesh0/Primitive0", path)),
        );
    }
    scenes.scene_registry = scene_registry;
    meshes.mesh_registry = mesh_registry;
}
```

## What went wrong

```
thread 'main' panicked at 'internal error: entered unreachable code: entries should always be valid after a flush', C:\Users\voice\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_asset-0.12.1\src\assets.rs:148:13
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library\std\src\panicking.rs:593
   1: core::panicking::panic_fmt
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library\core\src\panicking.rs:67
   2: bevy_asset::assets::DenseAssetStorage<bevy_gltf::Gltf>::insert
             at C:\Users\voice\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_asset-0.12.1\src\assets.rs:148
   3: bevy_asset::assets::Assets<bevy_gltf::Gltf>::insert_with_index
             at C:\Users\voice\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_asset-0.12.1\src\assets.rs:349
   4: bevy_asset::assets::Assets<bevy_gltf::Gltf>::insert<bevy_gltf::Gltf,enum2$<bevy_asset::id::AssetId<bevy_gltf::Gltf> > >
             at C:\Users\voice\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_asset-0.12.1\src\assets.rs:311
   5: bevy_asset::loader::impl$5::insert<bevy_gltf::Gltf>
             at C:\Users\voice\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_asset-0.12.1\src\loader.rs:240
   6: bevy_asset::server::info::AssetInfos::process_asset_load
             at C:\Users\voice\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_asset-0.12.1\src\server\info.rs:326
   7: bevy_asset::server::handle_internal_asset_events::closure$0
             at C:\Users\voice\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_asset-0.12.1\src\server\mod.rs:940
   8: bevy_ecs::world::World::resource_scope<bevy_asset::server::AssetServer,tuple$<>,bevy_asset::server::handle_internal_asset_events::closure_env$0>
             at C:\Users\voice\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.12.1\src\world\mod.rs:1571
   9: bevy_asset::server::handle_internal_asset_events
             at C:\Users\voice\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_asset-0.12.1\src\server\mod.rs:935
 ...
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Encountered a panic in exclusive system `bevy_asset::server::handle_internal_asset_events`!
Encountered a panic in system `bevy_app::main_schedule::Main::run_main`!
```

## Additional information
The same panic was investigated in https://github.com/bevyengine/bevy/issues/10444. It seems this same code is also panicking, but it appears to be unrelated to AssetEvent::Removed this time, since assets are not being removed in this case.

For debugging purpose, I've included the assets that are being loaded in the example above here: https://drive.google.com/file/d/1Nq9fBoARR6p9nxXc-aOJt2Lut5-UpZMP/view?usp=sharing. The assets are from Mixamo and Qauternius's Ultimate Animated Animal Pack.

**Comment by Testare** [comment]
I've been getting this error as well

**Comment by Testare** [comment]
A little more information about the error on my end (to help with debugging):

First of all, my error isn't occurring for `DenseAssetStorage<bevy_gltf::Gltf>::insert` specifically, or rather not for that specific generic. In fact, the error trace is just showing generic parameter `A`. Here's a trace:

```
thread 'main' panicked at /Users/logwoo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_asset-0.12.1/src/assets.rs:148:13:
internal error: entered unreachable code: entries should always be valid after a flush
stack backtrace:
   0: rust_begin_unwind
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
   2: bevy_asset::assets::DenseAssetStorage<A>::insert
             at /Users/logwoo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_asset-0.12.1/src/assets.rs:148:13
   3: bevy_asset::assets::Assets<A>::insert_with_index
             at /Users/logwoo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_asset-0.12.1/src/assets.rs:349:24
   4: bevy_asset::assets::Assets<A>::insert
             at /Users/logwoo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_asset-0.12.1/src/assets.rs:305:17
   5: <A as bevy_asset::loader::AssetContainer>::insert
             at /Users/logwoo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_asset-0.12.1/src/loader.rs:240:9
   6: bevy_asset::server::info::AssetInfos::process_asset_load
             at /Users/logwoo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_asset-0.12.1/src/server/info.rs:326:9
   7: bevy_asset::server::handle_internal_asset_events::{{closure}}
             at /Users/logwoo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_asset-0.12.1/src/server/mod.rs:940:21
   8: bevy_ecs::world::World::resource_scope
             at /Users/logwoo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.12.1/src/world/mod.rs:1571:22
   9: bevy_asset::server::handle_internal_asset_events
             at /Users/logwoo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_asset-0.12.1/src/server/mod.rs:935:5
```

I don't think I even have bevy_gltf compiled in my game, as it's more of a TUI game. In my case, I also have custom asset loaders, including assets that depend on other assets.

Secondly, I also get a second type of error, with this trace:
```
thread 'main' panicked at /Users/logwoo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_asset-0.12.1/src/assets.rs:305:54:
called `Result::unwrap()` on an `Err` value: InvalidGenerationError { index: AssetIndex { generation: 0, index: 17 }, current_generation: 1 }
stack backtrace:
   0: rust_begin_unwind
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/result.rs:1652:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/result.rs:1077:23
   4: bevy_asset::assets::Assets<A>::insert
             at /Users/logwoo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_asset-0.12.1/src/assets.rs:305:17
   5: <A as bevy_asset::loader::AssetContainer>::insert
             at /Users/logwoo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_asset-0.12.1/src/loader.rs:240:9
   6: bevy_asset::server::info::AssetInfos::process_asset_load
             at /Users/logwoo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_asset-0.12.1/src/server/info.rs:326:9
   7: bevy_asset::server::handle_internal_asset_events::{{closure}}
             at /Users/logwoo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_asset-0.12.1/src/server/mod.rs:940:21
   8: bevy_ecs::world::World::resource_scope
             at /Users/logwoo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.12.1/src/world/mod.rs:1571:22
   9: bevy_asset::server::handle_internal_asset_events
             at /Users/logwoo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_asset-0.12.1/src/server/mod.rs:935:5
  10: core::ops::function::FnMut::call_mut
```

The result is unwrapped on line 305, but the `Err(InvalidGenerationError)` actually comes from the same function as the other error, just a few lines up: https://github.com/bevyengine/bevy/blob/v0.12.1/crates/bevy_asset/src/assets.rs#L142

**Comment by mockersf** [comment]
For the original issue, I think it's because you're only keeping a strong handle to the subassets (`#Scene0` and `#Mesh0/Primitive0`), and the handle to the main asset is dropped too early, before the asset matching is actually inserted. This insertion is what is causing the panic.

It can probably happen every time an asset is loaded with a label, and the main asset is ignored, but it seems random and load dependent.

As a workaround in user code, you can keep a strong handle to the main asset (a `Gltf` here) and drop it once every thing is loaded

**Comment by marcelchampagne** [comment]
@mockersf Thank you so much for investigating! I tried your suggested workaround and it seems to have resolved the issue (unless I've yet to encounter the panic yet 😅). Your hypothesis makes a lot of sense though and would explain why others may not be encountering it. Still I'm somewhat surprised given that loading a GLTF Scene without the entire Gltf file is probably one of the most common things I'd expect users to do with GLTF files.

But as we observed since it's load dependent but the race condition only really occurs when lots of assets are being loaded.

**Comment by marcelchampagne** [comment]
Can confirm that the workaround fix is indeed working been running with it for a couple of days. I also doubled checked and my full application code still panics 1/5 times without it so @mockersf assessment of the issue is accurate at least for my case.

Unrelated but GLTF assets in general take much longer to load in 0.12 than in 0.11.x. Just an FYI but loading 200 assets is taking ~8 seconds for me now and it was maybe ~1 second before, if there isn't an existing issue for that happy to file one, but it's causing iteration time to be a fair bit longer.

**Comment by AxiomaticSemantics** [comment]
This may have possibly been resolved by #11986
I'll keep trying to reproduce and follow-up on the results later. To anyone that does get this, could you try on current main?

**Comment by cornytrace** [comment]
@AxiomaticSemantics I can confirm that the issue still exists on main branch

**Comment by cornytrace** [comment]
For me the error didn't stop occurring until I put both the main asset and the sub-assets in static Mutex<Vec<Handle<_>>>, only the main assets or only the sub assets still produced the issue.

**Comment by Testare** [comment]
I don't suppose any progress has been made on this issue?

**Comment by Aronry** [comment]
Welp, as far as I'm reading here, this issue can be "fixed" by never doing sub-asset loads, and only loading "Handle<Gltf>"s, and accessing elements from there. This is how "bevy_gltf_components" loads everything, for example. Seems to be working for me so far, will report back if I happen to see this error again.

**Comment by ricky26** [comment]
I've done some investigation into this issue, and I think I know where the problem lies, but it's a tricky one to fix.

I managed to get the reproduction rate up by limiting `bevy` to handling one asset event per frame (which I don't think invalidates the investigation). I also managed to get it to happen by calling `AssetServer::reload`.

What I think is happening is this:
- Loading multiple labelled assets from the same path results in the main asset actually getting loaded multiple times in `AssetServer::load_internal`, but sharing the same handle. (This is timing-dependent: all load operations have to be started before the first time the main asset finishes loading.) This seems like a bug, however it shouldn't be totally invalid, because it's only as bad as doing some superfluous `reload()`s.
- When the loads complete, they race. _If one of the `Loaded` events is handled in a later frame to the others, the crash will occur._ All but the last load will be fine, because the loading process holds a copy of the handle. These completed loads will produce events which result in `Assets<A>::insert` being called with the loaded asset.
- However, on the last load, once the event is written, the handle will be dropped. For labelled assets, this handle is a handle to the main asset - which we don't keep, and this causes the handle data to be dropped, which in turn removes the asset index from `Assets<A>`. For most assets, this is inhibited when the asset is in the middle of loading - however, this same grace doesn't apply for assets _which have already loaded or failed to load at least once_.

I've been pondering it a bit, and I've come up with a couple of semi-sensible solutions:
- Make `InternalAssetEvent::Loaded` include a handle for the asset, so that it's kept alive until the insert has completed. This will possibly waste resources, since we're keeping the handle alive whilst loading is ongoing. (If this is done, the code-path that prevents loading assets from being dropped can be removed.)
- Change the condition for "loading assets" to be a separate atomic integer, which we always increment when we start loading and decrement afterwards, no longer using the `LoadState` as a metric for when the handle is safe to drop. This will still result in the asset being successfully inserted, but at least the rest of the system considers the handle dead.

Either way, I think it's probably a good idea to remove `Loading` from `LoadState` and track it separately, because `Loaded` and `Loading` are not mutually-exclusive states.

**Comment by ricky26** [comment]
Turns out I was probably over-thinking the solution. Since the handle is an asset-server-managed, I can just check whether it's been removed from the list of asset IDs we know about, and skip inserting it into `Assets<A>`. This probably also removes the need for the workaround when dropping handles.

If anyone has the means and a project which triggers this issue, testing with that fix would be much appreciated.

**Comment by Testare** [comment]
I have a project, but with the new release coming up there are bound to be other problems when I switch to targeting main/your PR. But since I don't want to wait until 0.15 for this fix, I'mma give it a shot, maybe try temporarily deleting extraneous plugins until I get a pared down version that still reproduces the error.

**Comment by ricky26** [comment]
@Testare I've backported the change to 0.13.2, to make it a bit easier to test. You should be able to do:

```toml
[dependencies]
bevy = { git = "https://github.com/ricky26/bevy.git", branch = "bugfix/labelled-asset-loading-0.13" }
```
In your Cargo.toml.

**Comment by Testare** [comment]
Oh sorry didn't see this XD I appreciate the effort though! Regardless, the migration to main was rather smooth this time, and this'll probably give more accurate results anyways.

So using bevyengine/bevy:main, I was able to reproduce the error after a couple runs. In fact, the error was much longer than before, which would probably be a good thing for debugging. I could include that trace here but...

When I was tracking your PR, I was not able to reproduce the crash! I even had a loop something like `for x in {1..40} ; do cargo run ; done` , and it never crashed. I'm not doing the math for `p < 0.05`, but looks pretty likely this PR fixes the issue =]

**Comment by ricky26** [comment]
Thanks for taking the time to check @Testare. :slightly_smiling_face:

**Comment by Testare** [comment]
Thanks for taking the time to fix! I would be quite sad to wait until 0.15 for this =]
