### ISSUE TITLE
Despawned UI Nodes' parents' children need to be updated in UiSurface BEFORE despawn

### ISSUE THREAD

**Issue by eidloi** [bevyengine/bevy#12403]
## Bevy version
0.13

## What you did

Manipulating UI elements sometimes need cleanup. 

## What went wrong

Calling `commands.entity(entity).despawn_recursive();` can cause `taffy` to panic:

```
thread 'Compute Task Pool (10)' panicked at \...\.cargo\registry\src\index.crates.io-6f17d22bba15001f\taffy-0.3.18\src\node.rs:285:25:
invalid SlotMap key used
```

This is apparently because the entity is removed from `taffy` before the relevant children/parent is cleaned up, leaving invalid `SlotMap` keys that cannot be looked up when the child/parent relationship is updated. 

However, the origin of this error is from the initial creation of the node hierarchy, meaning that when the node layout is added, somehow `taffy` doesn't have the right reference. Rendering works fine, but trying to despawn a broken entity regardless of where the despawn is started in the hierarchy from always causes the panic. *Might* be related to entity versions, but it's just a feeling.

## Additional information

After two weeks of pulling all-nighters (and my hair) I have this `EntityCommand` that can safely remove broken entities (naming altered for politeness):

``` rust
struct UntuckThisBirch;
impl EntityCommand for UntuckThisBirch{
    fn apply(self, id: Entity, world: &mut World) {
        let Ok(parent) = world.query::<&Parent>().get(world, id) else {
            return;
        };

        let parent_id = parent.get();
        let Ok(parent_children) = world.query::<&Children>().get(world, parent_id) else {
            return;
        };

        let children: Vec<Entity> = parent_children
            .iter()
            .filter(|child| **child != id)
            .map(|child| *child)
            .collect();
        let mut parent = world.entity_mut(parent_id);
        parent.replace_children(&children);

        world.resource_scope(|world, mut ui_surface: Mut<UiSurface>| {
            let Ok(parent_children) = world.query::<&Children>().get(world, parent_id) else {
                return;
            };

            ui_surface.update_children(parent_id, parent_children);
        });

        world.despawn(id);
    }
}
```

It is called in context like so:

``` rust
commands.entity(entity).despawn_descendants();
commands.entity(entity).add(UntuckThisBirch);
```

NOTE: The above command works, and I can despawn the broken entity _targetedly_. **HOWEVER, calling `despawn_descendants` from higher up in the hierarchy without removing the broken entity first also causes the same panic!**

**Comment by eidloi** [comment]
It is probably the ORDER of creation of the nodes, rather than the structure. It might be that cleaning up in taffy is sensitive to the order the elements were added, as in, the elements need to be created root-to-leaf. Jumping around, creating siblings, parents, re-parenting, etc. is out of order in taffy, so cleanup of branches happen before leaves.

**Comment by eidloi** [comment]
I found a stable solution, but it needs to be added manually anywhere serious UI manipulation happens:

``` rust
pub struct ResetChildrenInUiSurface;
impl EntityCommand for ResetChildrenInUiSurface {
    fn apply(self, id: Entity, world: &mut World) {
        world.resource_scope(|world, mut ui_surface: Mut<UiSurface>| {
            let Ok(children) = world.query::<&Children>().get(world, id) else {
                return;
            };
            ui_surface.update_children(id, children);
        });
    }
}
```

NOTE: This needs to be done _after_ the UI system builds at least once. Newly created nodes will not be upsert'd into the UiSurface before that (and the upsert is private due to the LayoutConfig being private), so they just throw a warning skipping new children. Interestingly, this works as well, but the warning is annoying.

**Comment by StrikeForceZero** [comment]
I've added some [tests](https://github.com/bevyengine/bevy/pull/12804/files#diff-5c400b2e41f9544b35a0aecff4885259e19f56cfe5ad96174db742d8e5128a44R1138-R1217) to https://github.com/bevyengine/bevy/pull/12804 that might match your scenario. 

If you have time, could you test that branch against it and see if it's fixed?

**Comment by eidloi** [comment]
@StrikeForceZero I didn't commit the broken versions unfortunately, and I am still not 100% sure what trips it. If I have the time I'll try to conjure up something.

**Comment by eidloi** [comment]
The issue is still present in [v0.14.0-rc.3](https://github.com/bevyengine/bevy/releases/tag/v0.14.0-rc.3). Since `UiSurface` has been made private applying the fix is no longer possible.

NOTE: Even if I make it public and try my previous fix, it no longer works, and just ends up panicking again.

**Comment by eidloi** [comment]
> I've added some [tests](https://github.com/bevyengine/bevy/pull/12804/files#diff-5c400b2e41f9544b35a0aecff4885259e19f56cfe5ad96174db742d8e5128a44R1138-R1236) to #12804 that might match your scenario.
> 
> If you have time, could you test that PR/branch against it and see if it's fixed?

Sorry for the absolute delay. I cherry picked your two commits from the PR on top of https://github.com/bevyengine/bevy/releases/tag/v0.14.0-rc.3 but the issue remained.

**Comment by eidloi** [comment]
This issue can be reproduced in `sickle_ui`

Checkout https://github.com/UmbraLuminosa/sickle_ui/tree/55405d0c4bc39be0a7937d936eb9235b11916a7b
Comment out the line https://github.com/UmbraLuminosa/sickle_ui/blob/55405d0c4bc39be0a7937d936eb9235b11916a7b/examples/simple_editor.rs#L526

Start the example cargo run --example simple_editor
Select `Layout` from the `Showcase` menu, then right-click any of the tabs and choose `Popout`. 

Closing the floating panel with the `X` will cause the crash.

NOTE: The branch points to local bevy folder instead of the repo!

**Comment by StrikeForceZero** [comment]
> > I've added some [tests](https://github.com/bevyengine/bevy/pull/12804/files#diff-5c400b2e41f9544b35a0aecff4885259e19f56cfe5ad96174db742d8e5128a44R1138-R1236) to #12804 that might match your scenario.
> > 
> > If you have time, could you test that PR/branch against it and see if it's fixed?
> 
> Sorry for the absolute delay. I cherry picked your two commits from the PR on top of https://github.com/bevyengine/bevy/releases/tag/v0.14.0-rc.3 but the issue remained.


I'm on mobile so I might be wrong but you'd likely need this PR applied which has the regression test cases for the despawn descendent:

https://github.com/bevyengine/bevy/pull/13360

I'll try and take a look tonight with your reproduction example.

**Comment by eidloi** [comment]
> I'm on mobile so I might be wrong but you'd likely need this PR applied which has the regression test cases for the despawn descendent:
> 
> #13360
> 
> I'll try and take a look tonight with your reproduction example.

This had a merge conflict with RC3 and there was a change (probably on the taffy side) that leaves the mod file red too, so I stopped trying since I don't know enough about it.

Thanks!

**Comment by StrikeForceZero** [comment]
> > I'm on mobile so I might be wrong but you'd likely need this PR applied which has the regression test cases for the despawn descendent:
> > #13360
> > I'll try and take a look tonight with your reproduction example.
> 
> This had a merge conflict with RC3 and there was a change (probably on the taffy side) that leaves the mod file red too, so I stopped trying since I don't know enough about it.
> 
> Thanks!

I've rebased the PR on top of the lastest from main so it should work now if you wanted to try. However, even **without** the changes, I wasn't able to reproduce the crash given your instructions. Closing the popped out tabs via your `bevy_014_upgrade` branch did not result in a crash.  Can you double check / and or test against the PR if you are still seeing the crash?

**Comment by eidloi** [comment]
> > > I'm on mobile so I might be wrong but you'd likely need this PR applied which has the regression test cases for the despawn descendent:
> > > #13360
> > > I'll try and take a look tonight with your reproduction example.
> > 
> > 
> > This had a merge conflict with RC3 and there was a change (probably on the taffy side) that leaves the mod file red too, so I stopped trying since I don't know enough about it.
> > Thanks!
> 
> I've rebased the PR on top of the lastest from main so it should work now if you wanted to try. However, even **without** the changes, I wasn't able to reproduce the crash given your instructions. Closing the popped out tabs via your `bevy_014_upgrade` branch did not result in a crash. Can you double check / and or test against the PR if you are still seeing the crash?

have you tried commenting out the line mentioned? Otherwise the issue doesn't show up.
In any case, I checked out your branch and it did not fix the issue. 

HOWEVER. I literally had a fever dream where I figured out the source of the problem, so I tracked that down and voila!

This line: 
https://github.com/bevyengine/bevy/blob/03f63e72cfdb1d8a305bd034b0088e850ed3f064/crates/bevy_ui/src/layout/mod.rs#L194 
Needs to move to L219. I _think_ the issue is with the queries, sometimes we remove the nodes from the slotmap before we try to update their children. (`RemovedComponent<Children>` will contain all entities form `RemovedComponents<Node>` as it is a subset of it.)

Someone who better understands the whole UI update process needs to validate this claim tho. But moving the line resolved the issue I had and I didn't see any adverse effect.

**Comment by StrikeForceZero** [comment]
> have you tried commenting out the line mentioned?

Apologies, my reading comprehension failed me last night. Commenting it out does trigger the crash. And you're correct about my PR not fixing the issue. I'll post some comments on your PR after reviewing.
