### ISSUE TITLE
building docs is failing

### ISSUE THREAD

**Issue by mockersf** [bevyengine/bevy#20386]
## Bevy version

since rust version 1.90.0-nightly (ba7e63b63 2025-07-29)

## What you did

look at https://github.com/bevyengine/bevy/actions/workflows/docs.yml

## What went wrong

https://github.com/bevyengine/bevy/actions/runs/16613386626/job/47000992910

It's failing, probably due to https://github.com/rust-lang/rust/issues/144752

## Additional information

Mostly tracking for our 0.17 milestone as this would block releasing (docs.rs builds with nightly)

**Comment by BD103** [comment]
I'm unable to reproduce this on MacOS, so I may have done something wrong or this is platform-specific.

<details>

Script I used, based off of [this run](https://github.com/bevyengine/bevy/actions/runs/16765393798/job/47469370640) and [this workflow file](https://github.com/bevyengine/bevy/actions/runs/16765393798/workflow):

```sh
rustup override set nightly-2025-08-06

RUSTDOCFLAGS='-Zunstable-options --cfg=docsrs --generate-link-to-definition --html-after-content docs-rs/trait-tags.html'
CARGO_INCREMENTAL='0'
RUSTFLAGS='--cfg docsrs_dep'

cargo doc \
  -Zunstable-options \
  -Zrustdoc-scrape-examples \
  --all-features \
  --workspace \
  --no-deps \
  --document-private-items \
  --exclude ci \
  --exclude errors \
  --exclude bevy_mobile_example \
  --exclude build-wasm-example \
  --exclude build-templated-pages \
  --exclude example-showcase
```

Output of `rustc -vV`:

```
rustc 1.91.0-nightly (ec7c02612 2025-08-05)
binary: rustc
commit-hash: ec7c02612527d185c379900b613311bc1dcbf7dc
commit-date: 2025-08-05
host: aarch64-apple-darwin
release: 1.91.0-nightly
LLVM version: 20.1.8
```

</details>

**Comment by BD103** [comment]
This should be fixed today or tomorrow, since https://github.com/rust-lang/rust/pull/145008 has been merged upstream.

**Comment by mockersf** [comment]
still failing for Bevy with rust version 1.91.0-nightly (ca7750494 2025-08-09): https://github.com/bevyengine/bevy/actions/runs/16864419485/job/47769314084
```
thread 'rustc' (13888) panicked at src/librustdoc/html/sources.rs:346:14:
only local crates should have sources emitted
```

**Comment by mockersf** [comment]
I can reproduce with `RUSTDOCFLAGS="-Zunstable-options --cfg=docsrs --generate-link-to-definition --html-after-content docs-rs/trait-tags.html" RUSTFLAGS="--cfg docsrs_dep" cargo +nightly doc -Zunstable-options -Zrustdoc-scrape-examples --all-features --workspace --no-deps --document-private-items --exclude ci --exclude errors --exclude bevy_mobile_example --exclude build-wasm-example --exclude build-templated-pages --exclude example-showcase` 

It doesn't fail if I don't enable `rustdoc-scrape-examples`

**Comment by alice-i-cecile** [comment]
cc @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
It was fixed in https://github.com/rust-lang/rust/pull/145008.

**Comment by mockersf** [comment]
@GuillaumeGomez https://github.com/rust-lang/rust/pull/145008 should have been in the latest nightly, and it failed again today on rust version 1.91.0-nightly (c8ca44c98 2025-08-10): https://github.com/bevyengine/bevy/actions/runs/16886529104/job/47835564754

**Comment by GuillaumeGomez** [comment]
Hum indeed, so something else. Gonna try to take a look tomorrow.

**Comment by BD103** [comment]
> Hum indeed, so something else. Gonna try to take a look tomorrow.

Thank you, I really appreciate all the work you've put into fixing random issues we've found!

**Comment by GuillaumeGomez** [comment]
Just tested locally and the bug didn't happen. I think the nightly didn't include it somehow? Gonna send a small PR that will allow to check it' :)

**Comment by BD103** [comment]
> I can reproduce with `RUSTDOCFLAGS="-Zunstable-options --cfg=docsrs --generate-link-to-definition --html-after-content docs-rs/trait-tags.html" RUSTFLAGS="--cfg docsrs_dep" cargo +nightly doc -Zunstable-options -Zrustdoc-scrape-examples --all-features --workspace --no-deps --document-private-items --exclude ci --exclude errors --exclude bevy_mobile_example --exclude build-wasm-example --exclude build-templated-pages --exclude example-showcase`
> 
> It doesn't fail if I don't enable `rustdoc-scrape-examples`

What OS are you running? I'm still unable to reproduce this on MacOS:

```sh
$ rustc -vV
rustc 1.91.0-nightly (523d3999d 2025-08-30)
binary: rustc
commit-hash: 523d3999dcd4bbd9a52661a29dbd7351a9c5fb03
commit-date: 2025-08-30
host: aarch64-apple-darwin
release: 1.91.0-nightly
LLVM version: 21.1.0
```

We might be able to fix this by swapping the runner to `macos-latest` instead of `ubuntu-latest`.

**Comment by mockersf** [comment]
> What OS are you running? I'm still unable to reproduce this on MacOS:

I'm on macOS, and I'm still able to reproduce today...

```
$ rustc +nightly -Vv
rustc 1.91.0-nightly (523d3999d 2025-08-30)
binary: rustc
commit-hash: 523d3999dcd4bbd9a52661a29dbd7351a9c5fb03
commit-date: 2025-08-30
host: aarch64-apple-darwin
release: 1.91.0-nightly
LLVM version: 21.1.0
```

> We might be able to fix this by swapping the runner to `macos-latest` instead of `ubuntu-latest`.

That wouldn't fix building on docs.rs, which is the main issue

**Comment by alice-i-cecile** [comment]
https://github.com/rust-lang/rust/pull/146091 by @janis-bhm may have solved this, correct?

**Comment by BD103** [comment]
It looks like it should, but the nightly with the fix won't be available until tomorrow or Thursday. We can wait until then :)

**Comment by mockersf** [comment]
working now
