### ISSUE TITLE
`path` in bevy_reflect doesn't support traversing into a map

### ISSUE THREAD

**Issue by DavidVonDerau** [bevyengine/bevy#5764]
## What problem does this solve or what need does it fill?

`bevy_reflect` allows path strings, e.g.

```rust
let value = *foo.get_path::<f32>("d[0].value").unwrap();
```

The `d[0]` in the above path is indexing into the `0th` entry of the list-like field `d`.

There is no equivalent notation for indexing into a map-like field.

## What solution would you like?

```rust
// Maps use syntax {'key'} to differentiate from list syntax [idx].
let value = *foo.get_path::<f32>("m{'key'}.value").unwrap();
```

## What alternative(s) have you considered?

- It could use the same notation as lists, but that could be confusing, e.g. 
```rust
let value = *foo.get_path::<f32>("m[key].value").unwrap();
```
- Maybe there's no need for the quotes?
```rust
let value = *foo.get_path::<f32>("m{key}.value").unwrap();
```
- I suppose not adding support for this at all is another option.

## Additional context

n/a

**Comment by doup** [comment]
Maybe `m['key'].value` which similar to other languages.

**Comment by themasch** [comment]
I tried myself on a draft for this, but couldnt quite get it done right, as I was unable to get to the correct specific key typ used by the hash map. It could basically be anything that is `Hash + Reflect` afaict. 

I opted for the `m['key']` syntax for this implementation, as I found it the least suprising syntax. Also it clearly indicates that the user is expecting a map, not a list. 

We could also go for the `m[key]` route and either decide on seeing the ident (numeric or not) or check what the current value is (`List` or `Map`) and parse the ident acording to that. So you would either get an "Expected List, found Map" value for `map[0]`, or a "Expected map key, found list index". 

`map{key}` would make this even more clear, but I somehow feel that curly braces for map access isnt commonly used and would cause more fricition for the user? But unsure on that. 

## Beside choosing a syntax, from my point of view two other topic remain: 

1. The type juggling problem still is a road block for me. I am unsure on how to progress there. Rolling with "just use strings lel" as the draft does now, is not good imho. Reflection should provide the power to get to the real type there and a way to get from `&str` to the `Result<ProperKeyT, Errror>`, I am just not seeing it right now. 

2. what about arrays? In the code I found that beside `ReflectRef::Map` and `ReflectRef::List` there is also `ReflectRef::Array`. 
I think we want to handle them like lists, right? Should I create another PR to add this?

**Comment by MrGVSV** [comment]
Would this be resolved by #5812? (cc @themasch)

**Comment by themasch** [comment]
@MrGVSV  yeah #5812 was created to solve this, but as of know, I am still not able to solve that. 
I guess the right thing would be to close that PR and hope someone smarter than me comes around to fix it.
